all:
  hosts:
    resume_site:
      ansible_host: itaygueta.com
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/digitalocean_ssh_key
      domain_name: itaygueta.com
      beta_domain_name: beta.itaygueta.com
